=== jevrard/toposort/graphs/graph.dtd
<!ELEMENT graph (vertices,arrows)>

<!ELEMENT vertices (vertex+)>
<!ELEMENT vertex EMPTY>
<!ATTLIST vertex name CDATA #REQUIRED>

<!ELEMENT arrows (arrow+)>
<!ELEMENT arrow EMPTY>
<!ATTLIST arrow tail CDATA #REQUIRED>
<!ATTLIST arrow head CDATA #REQUIRED>

=== jevrard/toposort/graphs/graph2.xml
<?xml version='1.0' encoding="utf-8" ?>
<!DOCTYPE graph SYSTEM "graph.dtd">

<graph>
	<vertices>
		<vertex name="1"/>
    <vertex name="2"/>
    <vertex name="3"/>
    <vertex name="4"/>
    <vertex name="5"/>
	</vertices>
	<arrows>
		<arrow tail="2" head="1"/>
    <arrow tail="3" head="2"/>
    <arrow tail="3" head="4"/>
    <arrow tail="4" head="2"/>
	</arrows>
</graph>
